# Replace the '❯' symbol in the prompt with '➜' and '✘'
[character]
success_symbol = '[➜](bold green)'
error_symbol = '[✘](bold red)'

# Disable the prompt showing we're in a container
[container]
disabled = true

# Show that we use direnv
[direnv]
disabled = false

# Show how many commits we're ahead/behind
[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
